version: '3'

services:
    postgres:
        image: "postgres"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        expose:
            - 5432
        volumes:
            - ./database-vol:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        restart: on-failure
        ports:
            - 8080:80
        environment:
            PGADMIN_DEFAULT_EMAIL: hello@test.com
            PGADMIN_DEFAULT_PASSWORD: postgres
        volumes:
            - ./pgadmin-vol:/var/lib/pgadmin
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
