version: '3'

services:
    capture:
        build: ./capture
        container_name: capture
        volumes:
            - ./capture:/capture
            - ./videos:/videos
        environment: 
            - DISPLAY
        depends_on:
            - transform

    transform:
        build: ./transform
        container_name: transform
        volumes:
            - ./videos:/videos
        depends_on:
            - store

    store:
        build: ./store
        container_name: store
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - 5432:5432
            
networks:
    default:
        driver: bridge