version: '3'

services:

    zookeeper:
        image: debezium/zookeeper:1.6
        container_name: zookeeper
        ports:
            - 2181:2181
            - 2888:2888
            - 3888:3888
    
    kafka:
        image: debezium/kafka:1.6
        container_name: kafka
        ports:
            - 9092:9092
        environment:
            ZOOKEEPER_CONNECT: zookeeper:2181
            BOOTSTRAP_SERVER: kafka:9092
        depends_on:
            - zookeeper
    
    connect:
        image: debezium/connect:1.6
        container_name: connect
        restart: on-failure
        ports:
            - 8083:8083
        environment:
            GROUP_ID: 1
            CONFIG_STORAGE_TOPIC: my_connect_configs1
            OFFSET_STORAGE_TOPIC: my_connect_offsets1
            STATUS_STORAGE_TOPIC: my_connect_statuses1
            BOOTSTRAP_SERVERS: kafka:9092
        depends_on:
            - kafka
            - zookeeper
            
networks:
    default:
        driver: bridge